services:
  clamav:
    image: clamav/clamav-debian:stable
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ai-case-generator-demo_net

  redis:
    image: redis:8-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/projects/ai-case-generator-demo/redis:/data
    networks:
      - ai-case-generator-demo_net

  ai-case-generator-demo-backend:
    image: ai-case-generator-demo-backend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/projects/ai-case-generator-demo/data:/app/data
      - /opt/projects/ai-case-generator-demo/logs:/app/logs
      - /opt/projects/ai-case-generator-demo/models:/app/models
      - /opt/projects/ai-case-generator-demo/.env:/app/.env
    depends_on:
      - redis
      - clamav
    networks:
      - ai-case-generator-demo_net
      - gateway_net

  ai-case-generator-demo-frontend:
    image: ai-case-generator-demo-frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/projects/ai-case-generator-demo/logs:/app/logs
      - /opt/projects/ai-case-generator-demo/.streamlit:/app/.streamlit
    depends_on:
      - backend
    networks:
      - ai-case-generator-demo_net
      - gateway_net

networks:
  ai-case-generator-demo_net:
  gateway_net:
    external: true