[server]
host = "http://localhost:8000"
http_timeout = 30
upload_file_types = ["pdf", "jpg", "png"]
upload_file_max_size = 10485760

log_path = "./logs"
log_level = "INFO"
log_rotation_size = 100
log_retention_days = 7